/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CarType = IDL.Variant({
  'truck' : IDL.Null,
  'classic' : IDL.Null,
  'sport' : IDL.Null,
});
export const GameMode = IDL.Variant({
  'timeTrial' : IDL.Null,
  'singlePlayer' : IDL.Null,
});
export const ScoreEntry = IDL.Record({
  'car' : CarType,
  'player' : IDL.Principal,
  'mode' : GameMode,
  'time' : IDL.Nat32,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLeaderboard' : IDL.Func(
      [CarType, GameMode],
      [IDL.Vec(ScoreEntry)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'submitScore' : IDL.Func([CarType, GameMode, IDL.Nat32], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CarType = IDL.Variant({
    'truck' : IDL.Null,
    'classic' : IDL.Null,
    'sport' : IDL.Null,
  });
  const GameMode = IDL.Variant({
    'timeTrial' : IDL.Null,
    'singlePlayer' : IDL.Null,
  });
  const ScoreEntry = IDL.Record({
    'car' : CarType,
    'player' : IDL.Principal,
    'mode' : GameMode,
    'time' : IDL.Nat32,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLeaderboard' : IDL.Func(
        [CarType, GameMode],
        [IDL.Vec(ScoreEntry)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'submitScore' : IDL.Func([CarType, GameMode, IDL.Nat32], [], []),
  });
};

export const init = ({ IDL }) => { return []; };