/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CarType = { 'truck' : null } |
  { 'classic' : null } |
  { 'sport' : null };
export type GameMode = { 'timeTrial' : null } |
  { 'singlePlayer' : null };
export interface ScoreEntry {
  'car' : CarType,
  'player' : Principal,
  'mode' : GameMode,
  'time' : number,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLeaderboard' : ActorMethod<[CarType, GameMode], Array<ScoreEntry>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'submitScore' : ActorMethod<[CarType, GameMode, number], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];